name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: appdeeacr.azurecr.io
          username: appdeeacr
          password: T+KPn2IBXjuQsu3c9iJcVFTe4mco63Vx

 
    - name: Build and Push Docker image to Azure Container Registry
      run: |
           docker build . -t appdeeacr.azurecr.io/dotnetdocker:${{ github.sha }}
           docker push appdeeacr.azurecr.io/dotnetdocker:${{ github.sha }}
